[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[db.seed]
sql_paths = ["supabase/seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://www.changa.blog"]
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"

[functions."verify-email"]
verify_jwt = false

[functions."payment-initiate"]
verify_jwt = true

[functions."validate-review"]
verify_jwt = true

[functions."send-notifications"]
verify_jwt = true

[functions."log-event"]
verify_jwt = false
